#!/usr/bin/env bash
set -euo pipefail

readonly script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly expected_database_ip='172.31.250.10'
readonly expected_issuer='http://localhost:8090'
readonly openfga_key="${OPENFGA_PRESHARED_KEY:-local-openfga-api-key}"
cd "$script_dir/.."

tmp_files=()

pass() { echo "[verify] OK: $*"; }
fail() { echo "[verify] FAIL: $*" >&2; exit 1; }

cleanup() {
  local file
  for file in "${tmp_files[@]}"; do
    rm -f "$file"
  done
}
trap cleanup EXIT

container_id() {
  docker compose ps --quiet "$1"
}

assert_state() {
  local service=$1 expected=$2 id actual
  id="$(container_id "$service")"
  [[ -n "$id" ]] || fail "$service container does not exist"
  actual="$(docker inspect --format '{{.State.Status}}' "$id")"
  [[ "$actual" == "$expected" ]] || fail "$service is $actual, expected $expected"
}

assert_healthy() {
  local service=$1 id health
  id="$(container_id "$service")"
  assert_state "$service" running
  health="$(docker inspect --format '{{.State.Health.Status}}' "$id")"
  [[ "$health" == healthy ]] || fail "$service health is $health"
  pass "$service is running and healthy"
}

assert_host_mapping() {
  local service=$1 id hosts_file actual
  id="$(container_id "$service")"
  hosts_file="$(mktemp)"
  tmp_files+=("$hosts_file")
  docker cp "$id:/etc/hosts" "$hosts_file" >/dev/null
  actual="$(awk '$2 == "host.docker.internal" {print $1}' "$hosts_file")"
  [[ "$actual" == "$expected_database_ip" ]] \
    || fail "$service resolves host.docker.internal to ${actual:-nothing}, expected $expected_database_ip"
  pass "$service resolves host.docker.internal to $expected_database_ip"
}

for service in postgres-host zitadel zitadel-login openfga nginx-host; do
  assert_healthy "$service"
done

assert_host_mapping zitadel
assert_host_mapping openfga

migrate_id="$(docker compose ps --all --quiet openfga-migrate)"
[[ -n "$migrate_id" ]] || fail 'openfga-migrate container does not exist'
[[ "$(docker inspect --format '{{.State.ExitCode}}' "$migrate_id")" == 0 ]] \
  || fail 'openfga-migrate did not complete successfully'
pass 'OpenFGA migration completed before the service started'

docker compose exec -T zitadel-login node -e \
  "const fs=require('fs');const p='/zitadel-data/login-client.pat';if(!fs.statSync(p).isFile()||fs.statSync(p).size===0)process.exit(1)" \
  || fail 'Login V2 PAT is missing or empty'
pass 'Login V2 consumes the PAT generated by Zitadel'

database_clients="$(docker compose exec -T postgres-host runuser -u postgres -- \
  psql --dbname postgres --tuples-only --no-align --command \
  "SELECT datname || '|' || usename || '|' || client_addr FROM pg_stat_activity WHERE (datname, usename) IN (('zitadel','zitadel'),('openfga','openfga')) AND client_addr IS NOT NULL ORDER BY datname;")"
grep -Eq '^openfga\|openfga\|172\.31\.250\.' <<<"$database_clients" \
  || fail 'no OpenFGA database connection originates from 172.31.250.0/24'
grep -Eq '^zitadel\|zitadel\|172\.31\.250\.' <<<"$database_clients" \
  || fail 'no Zitadel database connection originates from 172.31.250.0/24'
pass 'Zitadel and OpenFGA reach PostgreSQL through the restricted 172.31.250.0/24 boundary'

docker compose exec -T nginx-host getent hosts zitadel >/dev/null \
  || fail 'nginx-host cannot resolve zitadel through Docker DNS'
docker compose exec -T nginx-host getent hosts zitadel-login >/dev/null \
  || fail 'nginx-host cannot resolve zitadel-login through Docker DNS'
docker compose exec -T nginx-host curl --fail --silent --show-error --connect-timeout 5 --max-time 15 \
  http://zitadel:8080/debug/ready >/dev/null \
  || fail 'nginx-host cannot reach Zitadel directly'

docker compose exec -T nginx-host curl --fail --silent --show-error --connect-timeout 5 --max-time 15 \
  http://zitadel-login:3000/ui/v2/login/healthy >/dev/null \
  || fail 'nginx-host cannot reach Zitadel Login V2 directly'
pass 'nginx resolves and reaches both real application upstreams'

curl --fail --silent --show-error --connect-timeout 5 --max-time 15 \
  http://127.0.0.1:8090/debug/ready >/dev/null \
  || fail 'full-path Zitadel readiness request failed'

discovery="$(curl --fail --silent --show-error --connect-timeout 5 --max-time 15 -H 'Host: localhost:8090' \
  http://127.0.0.1:8090/.well-known/openid-configuration)" \
  || fail 'full-path OIDC discovery failed'

issuer="$(sed -n 's/.*"issuer"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' <<<"$discovery")"
[[ "$issuer" == "$expected_issuer" ]] \
  || fail "unexpected OIDC issuer: ${issuer:-missing}, expected $expected_issuer"

curl --fail --silent --show-error --connect-timeout 5 --max-time 15 -H 'Host: localhost:8090' \
  http://127.0.0.1:8090/ui/v2/login/healthy >/dev/null \
  || fail 'full-path Login V2 health route failed'
pass 'client -> nginx -> Zitadel/Login V2 paths succeed with the expected issuer'

openfga_tmp="$(mktemp)"
tmp_files+=("$openfga_tmp")

openfga_code="$(curl --silent --show-error --connect-timeout 5 --max-time 15 \
  --output "$openfga_tmp" --write-out '%{http_code}' \
  -H "Authorization: Bearer $openfga_key" http://127.0.0.1:18081/stores)" \
  || fail 'authenticated OpenFGA request failed'

[[ "$openfga_code" == 200 ]] || fail "authenticated OpenFGA request returned HTTP $openfga_code"
grep -F '"stores"' "$openfga_tmp" >/dev/null \
  || fail 'OpenFGA response is not a stores document'
pass 'authenticated OpenFGA request succeeds through its diagnostic loopback port'

echo '[verify] All cross-component integration checks passed.'
